---
services:
  nginx: 
    image: nginx
    ports:
      - 7500:80
      # Use the line below to lock it down to only the host can use it, if you don't have a firewall setup like ufw.
      #- 127.0.0.1:7500:80
    volumes: 
      - ./data/nginx:/etc/nginx/
  shortener:
    image: shortener
    environment:
      DATABASE_URL: postgresql://data:data144donotexpose@db:5432/shortener
    depends_on:
      db:
        condition: service_healthy
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: data
      POSTGRES_PASSWORD: data144donotexpose
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5